
document.addEventListener("DOMContentLoaded", showResults);

// quiz result is generated by the amount of answer, 8 question in total so its divided among this
  //at least 65% to pass
//   function showResults() {
   
//     let percentage = localStorage.getItem("percentage");
//     const feedbackElement = document.getElementById('feedback');
  
//     if (percentage >= 65) {

//       feedbackElement.innerHTML = `<p style="color: green;">You passed with ${percentage}% correct! 🎉</p>`;

//     } else {

//       feedbackElement.innerHTML = `<p style="color: red;">You did not pass. Restarting the quiz...</p>`;
//       setTimeout(() => {
//         window.location.href = "level2.html";
//       }, 2000);
//     }
//   }

  function showResults() {

    let percentage = localStorage.getItem("percentage");
    const feedback = document.getElementById('feedback');
  
    if (percentage >= 65) {

      feedback.innerHTML = `<p style="color: green;">You passed with ${percentage}% correct! 🎉</p>`;

    } else {

      feedback.innerHTML = `<p style="color: red;">You did not pass. Restarting the quiz...</p>`;
      setTimeout(() => {
        window.location.href = "level2.html";
      }, 2000);
    }
  }